### ISSUE TITLE
Google Play sample app

### ISSUE THREAD

**Issue by bskierys** [bskierys/LockableViewPager#7]
Upload sample app to Google Play
- [ ] #8 Design new look for app 
- [ ] #9 Apply designed look and feel
- [ ] #10 Add about app last page to not confuse accidental users (and add link to github site)
- [ ] #11 Ci script to automate the process of app upload to Google Play
- [ ] #13 Arrows in sample app
